# Generated by Django 6.0.5 on 2026-05-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioGerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_responsavel', models.CharField(max_length=100)),
                ('quantidade_equipes', models.IntegerField()),
                ('nivel_hierarquico', models.CharField(choices=[('J', 'JUNIOR'), ('P', 'PLENO'), ('S', 'SENIOR')], max_length=1)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionariobase')),
            ],
        ),
    ]
