# Generated by Django 6.0.5 on 2026-05-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_rename_funcionariobase_funcionariobasemodel'),
        ('gerencia', '0002_funcionariogerencia_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuncionarioGerencia',
            new_name='FuncionarioGerenciaModel',
        ),
    ]
