# Generated by Django 6.0.5 on 2026-05-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_rename_funcionariobase_funcionariobasemodel'),
        ('gerencia', '0003_rename_funcionariogerencia_funcionariogerenciamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariogerenciamodel',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionariobasemodel'),
        ),
    ]
