# Generated by Django 6.0.5 on 2026-05-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0004_alter_funcionariogerenciamodel_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariogerenciamodel',
            name='nivel_hierarquico',
        ),
        migrations.RemoveField(
            model_name='funcionariogerenciamodel',
            name='nome',
        ),
    ]
