# Generated by Django 6.0.5 on 2026-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariobase',
            name='formacao',
            field=models.CharField(max_length=100),
        ),
    ]
