# Generated by Django 6.0.5 on 2026-05-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionariobase_formacao'),
        ('gerencia', '0002_funcionariogerencia_nome'),
        ('marketing', '0002_funcionariomarketing_nome'),
        ('ti', '0002_funcionarioti_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuncionarioBase',
            new_name='FuncionarioBaseModel',
        ),
    ]
