# Generated by Django 6.0.5 on 2026-05-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_rename_funcionariobase_funcionariobasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariobasemodel',
            name='area_atuacao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
