# Generated by Django 6.0.5 on 2026-05-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_atuacao', models.CharField(max_length=100)),
                ('graduacao', models.CharField(max_length=100)),
                ('redes_sociais', models.CharField(max_length=100)),
                ('campanhas_ativas', models.IntegerField()),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionariobase')),
            ],
        ),
    ]
