# Generated by Django 6.0.5 on 2026-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariomarketing',
            name='nome',
            field=models.CharField(default='Funcionario antigo', max_length=100),
            preserve_default=False,
        ),
    ]
