# Generated by Django 6.0.5 on 2026-05-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_rename_funcionariobase_funcionariobasemodel'),
        ('marketing', '0002_funcionariomarketing_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuncionarioMarketing',
            new_name='FuncionarioMarketingModel',
        ),
    ]
