# Generated by Django 6.0.5 on 2026-05-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0003_rename_funcionarioti_funcionariotimodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariotimodel',
            name='graduacao',
        ),
        migrations.RemoveField(
            model_name='funcionariotimodel',
            name='nome',
        ),
    ]
